### ISSUE TITLE
BeeGFS client issue

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azurehpc#119]
After deploying https://github.com/Azure/azurehpc/tree/master/examples/beegfs

I get: 
Stderr: Job for beegfs-client.service failed because the control process exited with error code. See "systemctl status beegfs-client.service" and "journalctl -xe" for details

CC team had a similar issue with rdma drivers being not available for the client to converge.

**Comment by garvct** [comment]
Can you try CentOS-HPC 7.7 and see if you see the same error?

**Comment by lmiroslaw** [comment]
the error is the same with CentOS-HPC 7.7:

Stderr: Job for beegfs-client.service failed because the control process exited with error code. See "systemctl status beegfs-client.service" and "journalctl -xe" for details.

BTW, the same problem is for beegfs-data-disk

**Comment by garvct** [comment]
Thanks, for checking.

It looks like the beegfs packages were updated on Nov 29, 2019 from 7.1.3 to 7.1.4. It appears that this update broke BeeGFS deployed in azurehpc on CentOS 7.7. I have created a branch called "beegfs_713" which deploys BeeGFS using the 7.1.3 packages instead of 7.1.4, all BeeGFS examples have been updated in this branch. I will create a PR later. Please try branch beegfs_713 and see if you can now deploy correctly.

**Comment by garvct** [comment]
Added PR #120

**Comment by lmiroslaw** [comment]
it worked! I just tested it with beegfs example. Thanks @garvct.
