### ISSUE TITLE
Benchmarking OpenFOAM

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azurehpc#122]
hi Team,

I would like to benchmark OpenFOAM motorbike case on SLURM cluster. For that I need to generate mesh with 50 millions cells.

Could you guide me how to modify [this script](https://github.com/Azure/azurehpc/blob/master/apps/openfoam_org/motorbike_benchmark/generate_mesh.sh) to do that?

**Comment by edwardsp** [comment]
I'm sure you will have done this by now since I am replying so late but to increase the size of the mesh you can increase the block mesh dimensions.  Here was the original benchmark that I did when at Intel with a table of blockmesh sizes to end mesh sizes - https://github.com/OpenFOAM/OpenFOAM-Intel/tree/master/benchmarks/motorbike.

I'll close this issue now (although if you still need more help just reopen).
